- name: Launch database
  docker_container:
    name: database
    image: pierrefrncs/devops:docker_tp2_database
    pull: yes
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD=pwd
      POSTGRES_USER=usr
      POSTGRES_DB=db