language: java
script:
#Test and Build app with docker
- cd ./simple-api/
- mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=pierrefrncs_dev2020
- cd ..

#Connexion à Docker
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

#Build
- docker build -t $DOCKER_USERNAME/devops:docker_tp2_simple_api simple_api
- docker build -t $DOCKER_USERNAME/devops:docker_tp2_database database
- docker build -t $DOCKER_USERNAME/devops:docker_tp2_httpd httpd

#Push sur Docker Hub
- docker push $DOCKER_USERNAME/devops:docker_tp2_simple_api
- docker push $DOCKER_USERNAME/devops:docker_tp2_database
- docker push $DOCKER_USERNAME/devops:docker_tp2_httpd

cache:
 directories:
 - $HOME/.m2

service: 
- docker

addons:
 sonarcloud:
  organization: "pierrefrncs-devops"
  token: "$SONARCLOUD_TOKEN"