language: java
script:
#Test and Build app with docker
- mvn clean verify --file ./simple-api/pom.xml

#Connexion à Docker
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

#Build
- docker build -t $DOCKER_USERNAME/devops:docker-tp2_simple-api simple-api
- docker build -t $DOCKER_USERNAME/devops:docker-tp2_database database
- docker build -t $DOCKER_USERNAME/devops:docker-tp2_httpd httpd

#Push sur Docker Hub
- docker push $DOCKER_USERNAME/devops:docker-tp2_simple-api
- docker push $DOCKER_USERNAME/devops:docker-tp2_database
- docker push $DOCKER_USERNAME/devops:docker-tp2_httpd

cache:
 directories:
 - $HOME/.m2

service: 
- docker
